// OCCUPATIONS
const OCCUPATION = {
    SCI_FI: [
        "Executivo de Bioengenharia",
        "Analista de Dados Neurais",
        "Arquiteto de Memórias Sintéticas",
        "Engenheiro de Replicantes",
        "Auditor de Inteligência Artificial",
        "Gerente de Colônia Off-World",
        "Especialista em Segurança Cibernética Corporativa",
        "Designer de Realidade Virtual",
        "Técnico de Implantes Cibernéticos",
        "Controlador de Drones Urbanos",
        "Caçador de Replicantes",
        "Detetive de Crimes Digitais",
        "Fiscal de Identidade Biométrica",
        "Operador de Vigilância por Satélite",
        "Agente de Supressão de IA",
        "Inspetor de Mercado Negro Tecnológico",
        "Oficial de Zona Radioativa",
        "Rastreador de Andróides Fugitivos",
        "Hacker de Megacorp",
        "Traficante de Implantes",
        "Falsificador de Identidade Digital",
        "Contrabandista Off-World",
        "Mecânico de Drones Hackeados",
        "Caçador de Dados (Data Hunter)",
        "Mercenário Cibernético",
        "Limpador de Cena Corporativa",
        "Técnico de Modificação Neural Ilegal",
        "Corretor de Memórias Roubadas",
        "Técnico de Manutenção de Neon",
        "Operador de Táxi Aéreo",
        "Comerciante de Peças Sintéticas",
        "Reparador de Próteses",
        "Agricultor Hidropônico Urbano",
        "Enfermeiro de Clínica de Implantes",
        "Programador Freelancer",
        "Sucateiro Tecnológico",
        "Vendedor de Chips Sensoriais",
        "Artista de Realidade Aumentada",
        "Curador de Personalidades Digitais",
        "Programador de Emoções Sintéticas",
        "Treinador de IA Autônoma",
        "Editor de Sonhos Virtuais",
        "Arqueólogo de Dados Perdidos",
        "Terapeuta de Trauma Digital",
        "Engenheiro de Upload Mental",
        "Moderador de Rede Neural Global",
        "Técnico de Backup de Consciência",
        "Designer de Avatares Corporativos",
        "Minerador de Asteroides",
        "Piloto de Carga Interplanetária",
        "Engenheiro de Terraformação",
        "Supervisor de Colônia Lunar",
        "Técnico de Atmosfera Artificial",
        "Segurança de Plataforma Orbital",
        "Mecânico de Nave Suborbital",
        "Coordenador de Migração Off-World",
        "Cartógrafo de Zona Radioativa",
        "Explorador de Ruínas Espaciais",
        "Influenciador de Realidade Aumentada",
        "Idol Virtual (consciência artificial famosa)",
        "Produtor de Sensações Digitais",
        "Jornalista de Guerra Corporativa",
        "Hacker de Transmissão Pública",
        "Diretor de Experiência Imersiva",
        "Editor de Memórias para Entretenimento",
        "Curador de Identidades Virtuais",
        "Performer de Clube Holográfico",
        "Técnico de Publicidade Neural",
        "Operador de Exoesqueleto de Combate",
        "Mercenário de Zona Corporativa",
        "Especialista em Guerra de Drones",
        "Técnico de Blindagem Cibernética",
        "Analista de Risco Urbano",
        "Sabotador Industrial",
        "Executor de Contratos Digitais",
        "Rastreador de Sinais Biométricos",
        "Operador de EMP Tático",
        "Guarda de Cofre de Dados",
        "Ladrão de Identidade Genética",
        "Modificador de DNA Ilegal",
        "Corretor de Segredos Corporativos",
        "Criador de IA Proibida",
        "Dealer de Simulação Sensorial",
        "Fornecedor de Passagens Off-Grid",
        "Médico de Implantes do Mercado Negro",
        "Especialista em Desaparecimento Digital",
        "Broker de Rebeldes Sintéticos",
        "Agente Duplo de Megacorp",
    ],
    MODERN: [
        "Desenvolvedor de Software",
        "Desenvolvedor Mobile",
        "Engenheiro de Dados",
        "Cientista de Dados",
        "Analista de Cibersegurança",
        "Designer UX/UI",
        "Especialista em Cloud Computing",
        "DevOps",
        "Product Manager",
        "QA Tester",
        "Social Media Manager",
        "Criador de Conteúdo",
        "Influenciador Digital",
        "Gestor de Tráfego Pago",
        "Copywriter",
        "Editor de Vídeo",
        "Especialista em SEO",
        "Community Manager",
        "Streamer",
        "Podcaster",
        "Analista Financeiro",
        "Consultor Empresarial",
        "Executivo de Vendas",
        "Gerente de Projetos",
        "Analista de RH",
        "Controller",
        "Empreendedor",
        "CEO",
        "Coordenador Administrativo",
        "Representante Comercial",
        "Enfermeiro",
        "Médico",
        "Fisioterapeuta",
        "Psicólogo",
        "Nutricionista",
        "Biomédico",
        "Técnico de Radiologia",
        "Terapeuta Ocupacional",
        "Designer Gráfico",
        "Diretor de Arte",
        "Fotógrafo",
        "Ilustrador",
        "Animador 3D",
        "Game Designer",
        "Roteirista",
        "Arquiteto",
        "Motorista de App",
        "Técnico de TI",
        "Eletricista",
        "Mecânico",
        "Chef de Cozinha",
        "Barista",
        "Personal Trainer",
        "Corretor de Imóveis",
    ],
    MEDIEVAL: [
        "OK",
    ],
    APOCALYPSE: [
        "OK",
    ],
    STEAMPUNK: [
        "OK",
    ],
    ROBOT: null,
}

OCCUPATION.ROBOT = OCCUPATION.SCI_FI

export { OCCUPATION }