// SCI-FI
const SCI_FI = {
    man: [
        "Kade",
        "Ryk",
        "Jex",
        "Soren",
        "Vance",
        "Dax",
        "Kieran",
        "Lucan",
        "Zane",
        "Ivo",
        "Malk",
        "Riven",
        "Cassian",
        "Jorik",
        "Nox",
        "Kade", 
        "Jax ",
        "Dren",
        "Kael",
        "Ryk ",
        "Nox ",
        "Vance",
        "Luc ",
        "Soren", 
        "Dex ",
        "Miro", 
        "Zane", 
        "Arik", 
        "Tyren", 
        "Cass",    
    ],
    fem: [
        "Lira",
        "Nyra",
        "Sable",
        "Kaia",
        "Veya",
        "Aris",
        "Elsyn",
        "Mira",
        "Ziva",
        "Kora",
        "Lyne",
        "Nira",
        "Vesper",
        "Aeryn",
        "Syl",
        "Nyra", 
        "Lira", 
        "Kaia", 
        "Sable", 
        "Veya", 
        "Elara", 
        "Mira", 
        "Aris", 
        "Syl ",
        "Nira", 
        "Vesper", 
        "Kora", 
        "Lyne", 
        "Ziva", 
        "Aeryn", 
    ]
}

const SCI_LAST_N = [
    "Vale",
    "Stroud",
    "Virex",
    "Kess",
    "Corvin",
    "Voss",
    "Calder",
    "Knox",
    "Dray",
    "Ryker",
    "Hale",
    "Crowe",
    "Drax",
    "Mirek",
    "Thorne",
    "Syntek",
    "Volen",
    "Ardyn",
    "Nexis",
    "Kyron",
    "Syntar",
    "Virell",
    "Omnitech",
    "Axion",
    "Zirek",
    "Kynex",
    "Vantor",
    "Helix",
    "Cyrex",
    "Novera",
    "Sato",
    "Ishida",
    "Volkov",
    "Kovacs",
    "Tanaka",
    "Moreau",
    "Kadez",
    "Arashi",
    "Virelli",
    "Nakamura",
    "Drakov",
    "Matsu",
    "Renko",
    "Arkwright",
    "Solari",
]

const ROBOTS = [
    "K-17",
    "LX-9",
    "Asha-3",
    "V1RA",
    "NX-04",
    "El-7",
    "Sera-9",
    "JXN",
    "Aria-12",
    "Unit K-6",
    "K-27 Vale",
    "LX-9 Sato",
    "AR-12 Nyra",
    "V1RA Kade",
    "NX-04 Stroud",
    "Unit D-6",
    "JXN-3",
    "Asha-9",
    "SERA-11",
    "Model V-8",
    "V",
]

export { SCI_FI, ROBOTS, SCI_LAST_N }